name: Build and Deploy with Toucan
on:
  push:
    branch:
      -main

jobs:
  deploy-page:
    uses: toucansites/github-workflows/.github/workflows/deploy.yml@main
    with:
      version: "1.0.0-beta.6"
      target: "live"
    permissions:
      contents: read
      pages: write
      id-token: write
