name: Build and Deploy with Toucan

#on:
#  push:
#    tags:
#      - 'v*'
#      - '[0-9]*'

on:
  push:
    branches: [feature/toucan-beta5]

jobs:
  deploy-page:
    uses: toucansites/github-workflows/.github/workflows/deploy.yml@feature/target-param
    permissions:
      contents: read
      pages: write
      id-token: write