name: Build and Deploy with Toucan

on:
  push:
    branches: [main]

jobs:
  deploy-page:
    uses: toucansites/github-workflows/.github/workflows/deploy.yml@feature/version-parameter
    with:
      version : "latest"
    permissions:
      contents: read
      pages: write
      id-token: write